### ISSUE TITLE
Support multicall3 on pulsechain mainnet

### ISSUE THREAD

**Issue by johnny-vu** [mds1/multicall#94] opened 2023-06-08 09:42 UTC
### Chain Name

PulseChain Mainnet

### Chain ID

369

### RPC URL

https://rpc.pulsechain.com

### Block Explorer URL

https://scan.pulsechain.com/

### Deployment Funds

Yes

**Comment by johnny-vu** [comment] 2023-06-08 10:26
@mds1 Hi, could you please take a look?

**Comment by mds1** [comment] 2023-06-08 16:12
My understanding from https://github.com/mds1/multicall/issues/43#issuecomment-1516703859 is that pulsechain is a fork of Ethereum, which seems to be confirmed by this:

```sh
code1=$(cast code 0xcA11bde05977b3631167028862bE2a173976CA11 --rpc-url https://rpc.pulsechain.com)
code2=$(cast code 0xcA11bde05977b3631167028862bE2a173976CA11 --rpc-url $MAINNET_RPC_URL)

if [ "$code1" = "$code2" ]
then
    echo "Code matches"
else
    echo "Code does not match"
fi
```

which prints `Code matches`. If that's correct, then I think I just need to update the [deployment file](https://github.com/mds1/multicall/blob/71ed3f610eac0be285e685f0a0376bcc40dcdfce/deployments.json#L372-L376) with other pulsechain networks?

**Comment by johnny-vu** [comment] 2023-06-08 16:25
Hi @mds1 thanks for your feedback.
Yes, you're right. PulseChain is a fork of Ethereum so we can use the same `multicall3` address.
Anw, do you have to release a new version to support the above PR?

**Comment by johnny-vu** [comment] 2023-06-08 16:40
> Sorry, what do you mean? It seems Multicall3 is currently on pulsechain mainnet at the regular 0xcA11bde05977b3631167028862bE2a173976CA11 address

My understanding is that we have to update [this](https://github.com/tellor-io/telliot-feeds/blob/main/setup.cfg#L71) to new version. But I'm not sure about it. Could you please let me know how I can use?

> If you can provide a list of (chain name, chain ID, block explorer URL, RPC URL) for all pusechain networks (mainnet/testnet) I can check if multicall3 is on each one and update the deployments list accordingly

For now, only pulsechain mainnet (chainId: 369) & testnet (chainId: 943).

**Comment by mds1** [comment] 2023-06-08 16:46
> My understanding is that we have to update [this](https://github.com/tellor-io/telliot-feeds/blob/main/setup.cfg#L71) to new version. But I'm not sure about it. Could you please let me know how I can use?

Ah I see. I'm not to familiar with the python ethereum ecosystem, but it seems that package is here: https://github.com/banteg/multicall.py

From a quick look at https://github.com/banteg/multicall.py/blob/master/multicall/constants.py#L115-L168, I don't see pulsechain, but you might be able to configure your own contract instance. I'd recommend asking in that repo :)

**Comment by mds1** [comment] 2023-06-08 16:47
I've also updated the deployments file to include pulsechain mainnet, so closing this issue

**Closed by mds1** 2023-06-08 16:47 UTC
Labels: Deployment Request

**Comment by johnny-vu** [comment] 2023-06-08 16:49
@mds1 thank you. I'm clear for now.
