### ISSUE TITLE
Problem: Multicalls on Polygon zkEVM crashes with error message

### ISSUE THREAD

**Issue by georgeciubotaru** [mds1/multicall#97] opened 2023-06-13 12:10 UTC
<img width="1410" alt="image" src="https://github.com/mds1/multicall/assets/8217518/f505ebd3-42cf-4b7d-8053-f980b14a98a2">

**Comment by mds1** [comment] 2023-06-13 15:00
Can you share more context and provide steps to reproduce? My guess is that you're using ethers.js and not using the `callStatic` modifier, so it's trying to execute a state-changing operation instead of just fetching data. Check out the [examples](https://github.com/mds1/multicall/tree/main/examples) too

**Comment by georgeciubotaru** [comment] 2023-06-13 15:11
hi @mds1 
<img width="1137" alt="image" src="https://github.com/mds1/multicall/assets/8217518/35b53c4b-31a6-4460-ab65-7ce4ee815b06">
<img width="698" alt="image" src="https://github.com/mds1/multicall/assets/8217518/171e8dfc-7d6c-40cd-865e-32ceae613938">


I've discovered that querying <8 calls worked, but if more then 8 then crashes. Using this function also on `Ethereum mainnet` and polygon without issues.

**Comment by georgeciubotaru** [comment] 2023-06-13 16:17
@invocamanman Yes

**Comment by invocamanman** [comment] 2023-06-13 16:22
sorry it also happen to me, will investigate this, thank you!

**Comment by georgeciubotaru** [comment] 2023-06-14 07:42
Temporary solution for me: Using batches (max 8 items)

**Comment by mds1** [comment] 2023-07-06 00:49
Just curious if there's any update on the cause or solution here?

**Comment by mds1** [comment] 2023-07-20 23:59
Going to close this since it seems like polygon zkEVM issue and not a multicall issue, hopefully it's been resolved :)

**Closed by mds1** 2023-07-20 23:59 UTC
